sonar.projectKey=GuiPiovezan_ci-with-sonnarcloud
sonar.organization=guipiovezan
sonar.sourceEncoding=UTF-8
sonar.sources=js/src/
sonar.exclusions=**/*.test.js
sonar.tests=js/src/
sonar.test.inclusions=**/*.test.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=js/coverage/lcov.info
sonar.host.url=http://localhost:9000