sonar.projectKey=GuiPiovezan_ci-with-sonnarcloud
sonar.organization=guipiovezan

sonar.sources=go/
sonar.exclusions=**/*_test.go

sonar.tests=go/
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=go/coverage.out